const products = [
    {
        name: "T-shirt with Tape Details",
        rating:  4.5,
        cost: 120,
        imgSrc: "/src/assets/images/products/1.png",
        discount: 0,
    },
    {
        name: "Skinny Fit Jeans",
        rating:  3.5,
        cost: 240,
        imgSrc: "/src/assets/images/products/2.png",
        discount: 20,
    },
    {
        name: "Checkered Shirt",
        rating:  4.5,
        cost: 180,
        imgSrc: "/src/assets/images/products/3.png",
        discount: 0,
    },
    {
        name: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        imgSrc: "/src/assets/images/products/4.png",
        discount: 30,
    },
    {
        name: "T-shirt with Tape Details",
        rating:  4.5,
        cost: 120,
        imgSrc: "/src/assets/images/products/5.png",
        discount: 0,
    },
    {
        name: "Skinny Fit Jeans",
        rating:  3.5,
        cost: 240,
        imgSrc: "/src/assets/images/products/6.png",
        discount: 20,
    },
    {
        name: "Checkered Shirt",
        rating:  4.5,
        cost: 180,
        imgSrc: "/src/assets/images/products/7.png",
        discount: 0,
    },
    {
        name: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        imgSrc: "/src/assets/images/products/8.png",
        discount: 30,
    },
    {
        name: "T-shirt with Tape Details",
        rating:  4.5,
        cost: 120,
        imgSrc: "/src/assets/images/products/9.png",
        discount: 0,
    },
    {
        name: "Skinny Fit Jeans",
        rating:  3.5,
        cost: 240,
        imgSrc: "/src/assets/images/products/10.png",
        discount: 20,
    },
    {
        name: "Checkered Shirt",
        rating:  4.5,
        cost: 180,
        imgSrc: "/src/assets/images/products/11.png",
        discount: 0,
    },
    {
        name: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        imgSrc: "/src/assets/images/products/12.png",
        discount: 30,
    },
    {
        name: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        imgSrc: "/src/assets/images/products/13.png",
        discount: 30,
    },
    {
        name: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        imgSrc: "/src/assets/images/products/14.png",
        discount: 30,
    },
    {
        name: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        imgSrc: "/src/assets/images/products/15.png",
        discount: 30,
    },
    {
        name: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        imgSrc: "/src/assets/images/products/16.png",
        discount: 30,
    },
]

export default products