const products = [
    {
        id: 0,
        mainSrc: "/src/assets/images/productDetailsPage/product1/1.png",
        src : ["/src/assets/images/productDetailsPage/product1/1.png",
        "/src/assets/images/productDetailsPage/product1/2.png", 
            "/src/assets/images/productDetailsPage/product1/3.png"],
        title : "One Life Graphic Tshirt",
        rating : 4.5,
        cost : 260,
        discount : 40,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"],
        gender: "Men",
        type: "T-shirt",
    },
    {
        id: 1,
        title: "Skinny Fit Jeans",
        rating:  3.5,
        cost: 240,
        mainSrc: "/src/assets/images/products/2.png",
        src: ["/src/assets/images/products/2.png","/src/assets/images/products/2.png","/src/assets/images/products/2.png"],
        discount: 20,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"],
        gender: "uniSex",
        type: "Jeans",
    },
    {
        id: 2,
        title: "Checkered Shirt",
        rating:  4.5,
        cost: 180,
        mainSrc: "/src/assets/images/products/3.png",
        src: ["/src/assets/images/products/3.png"],
        discount: 0,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 3,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/4.png",
        src: ["/src/assets/images/products/4.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 4,
        title: "T-shirt with Tape Details",
        rating:  4.5,
        cost: 120,
        mainSrc: "/src/assets/images/products/5.png",
        src: ["/src/assets/images/products/5.png"],
        discount: 0,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 5,
        title: "Skinny Fit Jeans",
        rating:  3.5,
        cost: 240,
        mainSrc: "/src/assets/images/products/6.png",
        src: ["/src/assets/images/products/6.png"],
        discount: 20,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 6,
        title: "Checkered Shirt",
        rating:  4.5,
        cost: 180,
        mainSrc: "/src/assets/images/products/7.png",
        src: ["/src/assets/images/products/7.png"],
        discount: 0,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 7,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/8.png",
        src: ["/src/assets/images/products/8.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 8,
        title: "T-shirt with Tape Details",
        rating:  4.5,
        cost: 120,
        mainSrc: "/src/assets/images/products/9.png",
        src: ["/src/assets/images/products/9.png"],
        discount: 0,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 9,
        title: "Skinny Fit Jeans",
        rating:  3.5,
        cost: 240,
        mainSrc: "/src/assets/images/products/10.png",
        src: ["/src/assets/images/products/10.png"],
        discount: 20,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 10,
        title: "Checkered Shirt",
        rating:  4.5,
        cost: 180,
        mainSrc: "/src/assets/images/products/11.png",
        src: ["/src/assets/images/products/11.png"],
        discount: 0,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 11,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/12.png",
        src: ["/src/assets/images/products/12.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 12,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/13.png",
        src: ["/src/assets/images/products/13.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 13,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/14.png",
        src: ["/src/assets/images/products/14.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 14,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/15.png",
        src: ["/src/assets/images/products/15.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 15,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/16.png",
        src: ["/src/assets/images/products/16.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 16,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/14.png",
        src: ["/src/assets/images/products/14.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 17,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/15.png",
        src: ["/src/assets/images/products/15.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 18,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/16.png",
        src: ["/src/assets/images/products/16.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 19,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/14.png",
        src: ["/src/assets/images/products/14.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 20,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/15.png",
        src: ["/src/assets/images/products/15.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 21,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/16.png",
        src: ["/src/assets/images/products/16.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 0,
        mainSrc: "/src/assets/images/productDetailsPage/product1/1.png",
        src : ["/src/assets/images/productDetailsPage/product1/1.png",
        "/src/assets/images/productDetailsPage/product1/2.png", 
            "/src/assets/images/productDetailsPage/product1/3.png"],
        title : "One Life Graphic Tshirt",
        rating : 4.5,
        cost : 260,
        discount : 40,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"],
        gender: "Men",
        type: "T-shirt",
    },
    {
        id: 1,
        title: "Skinny Fit Jeans",
        rating:  3.5,
        cost: 240,
        mainSrc: "/src/assets/images/products/2.png",
        src: ["/src/assets/images/products/2.png","/src/assets/images/products/2.png","/src/assets/images/products/2.png"],
        discount: 20,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"],
        gender: "uniSex",
        type: "Jeans",
    },
    {
        id: 2,
        title: "Checkered Shirt",
        rating:  4.5,
        cost: 180,
        mainSrc: "/src/assets/images/products/3.png",
        src: ["/src/assets/images/products/3.png"],
        discount: 0,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 3,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/4.png",
        src: ["/src/assets/images/products/4.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 4,
        title: "T-shirt with Tape Details",
        rating:  4.5,
        cost: 120,
        mainSrc: "/src/assets/images/products/5.png",
        src: ["/src/assets/images/products/5.png"],
        discount: 0,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 5,
        title: "Skinny Fit Jeans",
        rating:  3.5,
        cost: 240,
        mainSrc: "/src/assets/images/products/6.png",
        src: ["/src/assets/images/products/6.png"],
        discount: 20,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 6,
        title: "Checkered Shirt",
        rating:  4.5,
        cost: 180,
        mainSrc: "/src/assets/images/products/7.png",
        src: ["/src/assets/images/products/7.png"],
        discount: 0,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 7,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/8.png",
        src: ["/src/assets/images/products/8.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 8,
        title: "T-shirt with Tape Details",
        rating:  4.5,
        cost: 120,
        mainSrc: "/src/assets/images/products/9.png",
        src: ["/src/assets/images/products/9.png"],
        discount: 0,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 9,
        title: "Skinny Fit Jeans",
        rating:  3.5,
        cost: 240,
        mainSrc: "/src/assets/images/products/10.png",
        src: ["/src/assets/images/products/10.png"],
        discount: 20,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 10,
        title: "Checkered Shirt",
        rating:  4.5,
        cost: 180,
        mainSrc: "/src/assets/images/products/11.png",
        src: ["/src/assets/images/products/11.png"],
        discount: 0,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 11,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/12.png",
        src: ["/src/assets/images/products/12.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 12,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/13.png",
        src: ["/src/assets/images/products/13.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 13,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/14.png",
        src: ["/src/assets/images/products/14.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 14,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/15.png",
        src: ["/src/assets/images/products/15.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 15,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/16.png",
        src: ["/src/assets/images/products/16.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 16,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/14.png",
        src: ["/src/assets/images/products/14.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 17,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/15.png",
        src: ["/src/assets/images/products/15.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 18,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/16.png",
        src: ["/src/assets/images/products/16.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 19,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/14.png",
        src: ["/src/assets/images/products/14.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 20,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/15.png",
        src: ["/src/assets/images/products/15.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 21,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/16.png",
        src: ["/src/assets/images/products/16.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 0,
        mainSrc: "/src/assets/images/productDetailsPage/product1/1.png",
        src : ["/src/assets/images/productDetailsPage/product1/1.png",
        "/src/assets/images/productDetailsPage/product1/2.png", 
            "/src/assets/images/productDetailsPage/product1/3.png"],
        title : "One Life Graphic Tshirt",
        rating : 4.5,
        cost : 260,
        discount : 40,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"],
        gender: "Men",
        type: "T-shirt",
    },
    {
        id: 1,
        title: "Skinny Fit Jeans",
        rating:  3.5,
        cost: 240,
        mainSrc: "/src/assets/images/products/2.png",
        src: ["/src/assets/images/products/2.png","/src/assets/images/products/2.png","/src/assets/images/products/2.png"],
        discount: 20,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"],
        gender: "uniSex",
        type: "Jeans",
    },
    {
        id: 2,
        title: "Checkered Shirt",
        rating:  4.5,
        cost: 180,
        mainSrc: "/src/assets/images/products/3.png",
        src: ["/src/assets/images/products/3.png"],
        discount: 0,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 3,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/4.png",
        src: ["/src/assets/images/products/4.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 4,
        title: "T-shirt with Tape Details",
        rating:  4.5,
        cost: 120,
        mainSrc: "/src/assets/images/products/5.png",
        src: ["/src/assets/images/products/5.png"],
        discount: 0,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 5,
        title: "Skinny Fit Jeans",
        rating:  3.5,
        cost: 240,
        mainSrc: "/src/assets/images/products/6.png",
        src: ["/src/assets/images/products/6.png"],
        discount: 20,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 6,
        title: "Checkered Shirt",
        rating:  4.5,
        cost: 180,
        mainSrc: "/src/assets/images/products/7.png",
        src: ["/src/assets/images/products/7.png"],
        discount: 0,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 7,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/8.png",
        src: ["/src/assets/images/products/8.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 8,
        title: "T-shirt with Tape Details",
        rating:  4.5,
        cost: 120,
        mainSrc: "/src/assets/images/products/9.png",
        src: ["/src/assets/images/products/9.png"],
        discount: 0,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 9,
        title: "Skinny Fit Jeans",
        rating:  3.5,
        cost: 240,
        mainSrc: "/src/assets/images/products/10.png",
        src: ["/src/assets/images/products/10.png"],
        discount: 20,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 10,
        title: "Checkered Shirt",
        rating:  4.5,
        cost: 180,
        mainSrc: "/src/assets/images/products/11.png",
        src: ["/src/assets/images/products/11.png"],
        discount: 0,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 11,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/12.png",
        src: ["/src/assets/images/products/12.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 12,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/13.png",
        src: ["/src/assets/images/products/13.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 13,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/14.png",
        src: ["/src/assets/images/products/14.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 14,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/15.png",
        src: ["/src/assets/images/products/15.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 15,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/16.png",
        src: ["/src/assets/images/products/16.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 16,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/14.png",
        src: ["/src/assets/images/products/14.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 17,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/15.png",
        src: ["/src/assets/images/products/15.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 18,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/16.png",
        src: ["/src/assets/images/products/16.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 19,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/14.png",
        src: ["/src/assets/images/products/14.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 20,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/15.png",
        src: ["/src/assets/images/products/15.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
    {
        id: 21,
        title: "Sleeve Strped T-shirt",
        rating:  4.5,
        cost: 130,
        mainSrc: "/src/assets/images/products/16.png",
        src: ["/src/assets/images/products/16.png"],
        discount: 30,
        description : "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
        colors : ["#4F4631", "#31344F", "#314F4A"],
        sizes : ["Small", "Medium", "Large", "X-Large"]
    },
]

export default products